site_name: thunderpuck
site_description: thunder the puck
repo_url: https://github.com/dhamilton6/thunderpuck-repo
site_dir: site
copyright: Copyright &copy; 2019, <a href="https://github.com/dhamilton6">dhamilton6</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
