# Generated by Django 3.0.2 on 2020-02-11 02:26

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models

def create_initial_data(apps, schema):
    League = apps.get_model('leagues', 'League')
    League.objects.get_or_create(
        name='NHL',
        base_api_url='https://statsapi.web.nhl.com/',
        teams_json_url='api/v1/teams'
    )

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('base_api_url', models.URLField(null=True)),
                ('teams_json_url', models.URLField(null=True)),
                ('teams_json', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('teams_json_md5', models.CharField(max_length=32, null=True)),
            ],
        ),
        migrations.RunPython(create_initial_data)
    ]
